version: "3.9"

services:
  url-shortener:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: url_service
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    volumes:
      - .:/url
      - /url/node_modules
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: url_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: url_database
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
